# Site settings
author: Kevin Downs
title: The Little Coder That Could
header-img: img/home-bg.png
email: kevin.downs04@gmail.com
copyright_name: Kevin Downs
description: > # this means to ignore newlines until "baseurl:"
  Reflections and Things Learned at Flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kjdowns

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
